/* SPDX-License-Identifier: GPL-2.0 */
/* THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT! */
#include <stdint.h>

const char *version_daemon = "<unknown version>";
const char *version_fw_str = "hwsim-<unknown version>";
uint32_t version_fw = 0x00000004;
uint32_t version_api = 0x00000200;
